### ISSUE TITLE
GPU utilization in spark error

### ISSUE THREAD

**Issue by m15pradeep** [GoogleCloudDataproc/initialization-actions#1294]
I'm using attached install_gpu_driver.sh in dataproc 2.2. GPU is not getting recognized in spark. Attached installation logs for reference

[dataproc-gpu-main.txt](https://github.com/user-attachments/files/18652635/dataproc-gpu-main.txt)
[dataproc-initialization-script-0.log](https://github.com/user-attachments/files/18652636/dataproc-initialization-script-0.log)
[install_gpu_driver.txt](https://github.com/user-attachments/files/18652634/install_gpu_driver.txt)

Command:
**Library: tensorflow[and-cuda]
import tensorflow as tf
print(tf.config.list_physical_devices('CPU'))
print(tf.config.list_physical_devices('GPU'))**

Log:
2025-02-04 06:04:29.413125: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-04 06:04:31.327492: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1738649071.978220 80542 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1738649072.400870 80542 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-04 06:04:36.546724: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-02-04 06:04:50.776297: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2025-02-04 06:04:50.776349: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:137] retrieving CUDA diagnostic information for host: gpu-nvidia-l4-a363a292-a17a0463-m
2025-02-04 06:04:50.776359: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:144] hostname: gpu-nvidia-l4-a363a292-a17a0463-m
2025-02-04 06:04:50.776482: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:168] libcuda reported version is: 570.86.15
2025-02-04 06:04:50.776521: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:172] kernel reported version is: 570.86.15
2025-02-04 06:04:50.776531: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:259] kernel version seems to match DSO: 570.86.15
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
[]

**Comment by cjac** [comment]
Hello Pradeep,

Can you please tell me which GPU you are attempting to utilize?

The current gpu installer requires that you select a dataproc image version equal or less than `2.0.67-debian10`, `2.1.46-debian11` or `2.2.3-debian12` due to a recent policy change in the Linux kernel.

If you can tell me what GPU you have attached, and what version of CUDA/kernel driver you are targeting, I will be able to help further.

C.J.

**Comment by m15pradeep** [comment]
Hi CJ,

My requirement is all GPUs available under the region should work based with **2.2-debian12** image and the default CUDA/Kernel driver version is sufficient

For example, if region us-east4 is selected, all the listed GPUs should work

![Image](https://github.com/user-attachments/assets/57e259b3-355d-443e-a3cd-eb798d28ff6d)

Regards,
Pradeep

**Comment by cjac** [comment]
Okay, I'm working on that now.  Do you want a link to pre-release for testing, or would you like to wait until I publish it to GCS?

**Comment by m15pradeep** [comment]
Hi CJ,

Thank you for the update. Do you have any timeline when this will be published to GCS?

Regards,
Pradeep

**Comment by cjac** [comment]
My guess is within the next two weeks.

I'd like to bring your attention to this section of the README.md, however:

https://github.com/GoogleCloudDataproc/initialization-actions?tab=readme-ov-file#how-initialization-actions-are-used

---

**:warning: NOTICE:** For production usage, before creating clusters, it is strongly recommended
that you copy initialization actions to your own Cloud Storage bucket to guarantee consistent use of the
same initialization action code across all Dataproc cluster nodes and to prevent unintended upgrades
from upstream in the cluster:

```bash
BUCKET=<your_init_actions_bucket>
CLUSTER=<cluster_name>
gsutil cp presto/presto.sh gs://${BUCKET}/
gcloud dataproc clusters create ${CLUSTER} --initialization-actions gs://${BUCKET}/presto.sh
```

**Comment by cjac** [comment]
Note also that there is a new, as-yet-undocumented feature which is still likely to change before being codified in the readme.

Passing the `include-pytorch`[1] metadata attribute value as `yes` will install pytorch and tensorflow to a conda environment.  The name of the environment may be specified with the `gpu-conda-env`[2] metadata attribute.

[1] https://github.com/GoogleCloudDataproc/initialization-actions/blob/7e875225563b21680623ffc8bd04d8888aaef626/gpu/install_gpu_driver.sh#L1715
[2] https://github.com/GoogleCloudDataproc/initialization-actions/blob/7e875225563b21680623ffc8bd04d8888aaef626/gpu/install_gpu_driver.sh#L788

**Comment by cjac** [comment]
This change was merged with #1302

**Comment by m15pradeep** [comment]
Hi CJ,

Hope you are doing well. 

I used the latest [install_gpu_driver.sh](https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/gpu/install_gpu_driver.sh) but the script is getting stuck at the step below and timing out after 30 minutes, as per my timeout setting. Attached dataproc cluster setting and the logs.
**+ eval 'make -j4 pkg.debian.build'**

[dataproc_config.log](https://github.com/user-attachments/files/19109938/dataproc_config.log)
[install_gpu_driver.log](https://github.com/user-attachments/files/19109939/install_gpu_driver.log)

**Comment by cjac** [comment]
Please allocate 90 minutes for a 4-core instance's cache building initial run.  Or use an n1-standard-32 for this critical first step.  Subsequent runs for that version, os combination should perform much better once the cache is built.

**Comment by m15pradeep** [comment]
As you suggested, the cache is built with n1-standard-32, and training with the GPU is working successfully.

1. nvidia-tesla-p4 and nvidia-tesla-t4 are functioning as expected.

2. nvidia-a100-80gb - install_gpu_driver.sh is not supporting and failing in below,
if [[ "${gpu_count}" > "0" ]] ; then
    # N.B.: https://pci-ids.ucw.cz/v2.2/pci.ids.xz
    pci_device_id="$(grep -h -i PCI_ID=10DE /sys/bus/pci/devices/*/uevent | head -1 | awk -F: '{print $2}')"
    pci_device_id_int="$((16#${pci_device_id}))"
    case "${pci_device_id}" in
      "15F8" ) gpu_type="nvidia-tesla-p100" ;;
      "1BB3" ) gpu_type="nvidia-tesla-p4"   ;;
      "1DB1" ) gpu_type="nvidia-tesla-v100" ;;
      "1EB8" ) gpu_type="nvidia-tesla-t4"   ;;
      "20*"  ) gpu_type="nvidia-tesla-a100" ;;
      "23*"  ) gpu_type="nvidia-h100"       ;; # install does not begin with image 2.0.68-debian10/cuda11.1
      "27B8" ) gpu_type="nvidia-l4"         ;; # install does not complete with image 2.0.68-debian10/cuda11.1
    esac

    ACCELERATOR="type=${gpu_type},count=${gpu_count}"
  fi

3. nvidia-l4 - is failing "/tmp/install_gpu_driver.sh: line 286: is_cudnn8: command not found" for below configuration
--region us-east4 --single-node --master-machine-type g2-standard-12 --master-boot-disk-type pd-balanced --master-boot-disk-size 500 --master-accelerator type=nvidia-l4 --image-version 2.2-debian12

**Comment by m15pradeep** [comment]
As you suggested, the cache is built with n1-standard-32, and training with the GPU is working successfully.

1. nvidia-tesla-p4 and nvidia-tesla-t4 are functioning as expected

2. nvidia-l4 is failing to initialize with error **"/tmp/install_gpu_driver.sh: line 286: is_cudnn8: command not found"**--region us-east4 --master-machine-type g2-standard-12 --master-boot-disk-type pd-balanced --master-boot-disk-size 500 --master-accelerator type=nvidia-l4 --image-version 2.2-debian12

3. nvidia-a100-80gb is not supported due to below hardcode
```
if [[ "${gpu_count}" > "0" ]] ; then
    # N.B.: https://pci-ids.ucw.cz/v2.2/pci.ids.xz
    pci_device_id="$(grep -h -i PCI_ID=10DE /sys/bus/pci/devices/*/uevent | head -1 | awk -F: '{print $2}')"
    pci_device_id_int="$((16#${pci_device_id}))"
    case "${pci_device_id}" in
      "15F8" ) gpu_type="nvidia-tesla-p100" ;;
      "1BB3" ) gpu_type="nvidia-tesla-p4"   ;;
      "1DB1" ) gpu_type="nvidia-tesla-v100" ;;
      "1EB8" ) gpu_type="nvidia-tesla-t4"   ;;
      "20*"  ) gpu_type="nvidia-tesla-a100" ;;
      "23*"  ) gpu_type="nvidia-h100"       ;; # install does not begin with image 2.0.68-debian10/cuda11.1
      "27B8" ) gpu_type="nvidia-l4"         ;; # install does not complete with image 2.0.68-debian10/cuda11.1
    esac

    ACCELERATOR="type=${gpu_type},count=${gpu_count}"
  fi
```

Could you please check on item 2 and 3?

**Comment by cjac** [comment]
Thanks for this report Pradeep.  I'm glad to hear that your installer runtime was reduced when using a larger machine type.  Once cache has been built, you should be able to use a smaller machine type for subsequent builds.

Yes, I see that I should be less general with the A100 PCI device IDs.  I will test with the 80GB variant to ensure that it works as it should.

As for the L4 problem, I'm not certain what might be causing the problem, but I will try running the installer with the arguments you've provided.  Thank you for providing them, it will make my investigation easier.

**Comment by m15pradeep** [comment]
@cjac, after double-checking on the nvidia-l4, it turns out I hadn't properly reviewed the logs earlier, and it is actually working fine. Sorry for the confusion.

**Comment by cjac** [comment]
No sweat.  Thanks for double checking.  Can you add the switch line for the nvidia-tesla-a100-80g, and I'll review it?  I'm really booked solid right now and I could use the help.

**Comment by cjac** [comment]
Great.  Thank you; that will help a lot, but I was asking if you can review that URL on the line of the script that says NB: and update the following switch statement to include a line for the -80gb variant.

**Comment by cjac** [comment]
oh, nice.  they worked an `F5, Inc.` reference into the code.  Good work, team little red ball.  F5 still means acceleration.

```
case "${pci_device_id^^}" in
  ...
  "20F5" ) gpu_type="nvidia-tesla-a100-80gb" ;;
  "20*"  ) gpu_type="nvidia-tesla-a100" ;;
  ...
esac
```

**Comment by m15pradeep** [comment]
Hi @cjac, thank you for the update. The issue is now resolved, so I'm closing it.

I am facing some issues with assigning GPU resources to Spark executors. I will create a separate issue for that.

**Comment by cjac** [comment]
Thanks for the report! 

Here's an example of arguments to pass to spark jobs: 

https://github.com/cjac/initialization-actions/blob/2d3d53a990cf677fd208ae5ddf56a21b9d009564/gpu/test_gpu.py#L187
